### ISSUE TITLE
machineconfig update duplicate name

### ISSUE THREAD

**Issue by eifrach** [rh-ecosystem-edge/ztp-pipeline-relocatable#389]
update private registry cert machine config has the same name - which overwrites the master config and applies only for worker

```yaml
# for master
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master # <- role
  name: update-localregistry-ca-certs # <- same name
```

```yaml
# for worker
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker # <- role 
  name: update-localregistry-ca-certs  # <- same name 
```
