### ISSUE TITLE
Ansible cant login with root after ansible failure

### ISSUE THREAD

**Issue by eifrach** [rh-ecosystem-edge/ztp-pipeline-relocatable#464]
The Ansible playbook is changing the root password
```yaml
# https://github.com/rh-ecosystem-edge/ztp-pipeline-relocatable/blob/main/hack/deploy-hub-local/ansible/tasks/base/00-base-os.yaml#L139
- name: Update root user password
  ignore_errors: true 
  user:
    name: root
    password: "{{ root_password }}"
    append: yes
  when: root_update_pwd == True
  tags: [ 00-base-os ]
```
if you fail after this task, you wont be able to ssh to the host

we should insert the ssh keys before changing the root password
